#
# actuator_noise_reduction.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := actuator_noise_reduction
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ISP_DIR   := $(BSP_BOARD_CAMERA_MODULE_ISP_VERSION)
KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)/../interface
ccflags-y += -I$(KO_MODULE_PATH)/../sensor
ccflags-y += -I$(KO_MODULE_PATH)/$(ISP_DIR)/inc
ccflags-y += -I$(KO_MODULE_PATH)/../common

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
